name: build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, centos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: run install
      run: |
        yes | make install
