name: build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dotfiles
      run: |
        git clone https://github.com/averak/dotfiles $HOME/dotfiles
        cd $HOME/dotfiles
        yes | make install
